name       : qhull
version    : '2020.2'
release    : 1
source     :
    - http://www.qhull.org/download/qhull-2020-src-8.0.2.tgz : b5c2d7eb833278881b952c8a52d20179eab87766b00b865000469a45c1838b7e
license    : Qhull
component  : programming.library
summary    : Qhull computes the convex hull, Delaunay triangulation, Voronoi diagram, halfspace intersection about a point, furthest-site Delaunay triangulation, and furthest-site Voronoi diagram.
description: |
    Qhull computes the convex hull, Delaunay triangulation, Voronoi diagram, halfspace intersection about a point, furthest-site Delaunay triangulation, and furthest-site Voronoi diagram.
setup      : |
    %cmake
build      : |
    %make
install    : |
    %make_install
